
[env]
TERM = "xterm-256color"

[window]
padding = { x = 3, y = 3 }
dynamic_padding = true
decorations = "Buttonless"


[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
size = 14.0


[selection]
save_to_clipboard = true

[general]
import = [
    "~/.config/alacritty/themes/catppuccin_macchiato.toml"
]
